In [48]:
import pandas as pd
from collections import defaultdict, Counter
from os import listdir
from scipy.stats import itemfreq
import scipy.stats as stats
import numpy as np
import statistics
from statistics import mean
import csv
import re

In [2]:
pre_cats_interest_df = pd.read_csv("./results/stumbleon2_usercategoryinterest.csv")
post_cats_interest_df = pd.read_csv("./results/stumbleon2_usercategorypostinterest.csv")

In [3]:
users_ids = pre_cats_interest_df.user_id.unique()

In [4]:
similarities = []
for user_id in users_ids:
    pre =  pre_cats_interest_df[pre_cats_interest_df['user_id'] == user_id].category_id
    post = post_cats_interest_df[post_cats_interest_df['user_id'] == user_id].category_id
    similarities.append(len(set(pre) & set(post))/ ((len(pre)+len(post))-len(set(pre) & set(post))))

In [5]:
mean(similarities)

0.6178349428349428

In [6]:
user_interested_topics_dict = defaultdict(dict)
for user_id in users_ids:
    pre =  list(pre_cats_interest_df[pre_cats_interest_df['user_id'] == user_id].category_id)
    post = list(post_cats_interest_df[post_cats_interest_df['user_id'] == user_id].category_id)
    user_interested_topics_dict[user_id]['pre'] = pre
    user_interested_topics_dict[user_id]['post'] = post

In [7]:
users_approaches = pd.read_csv('users_approaches.csv')

# User topic interest before (pre) and after (post) using StumbleOn

In [118]:
for k, v in user_interested_topics_dict.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    print("Approach:", app,  "user_id:", k, v['pre'], v['post'])

Approach: adaptive user_id: 237 [115, 51, 66, 2, 80, 105] [115, 66, 2, 105]
Approach: adaptive user_id: 249 [71, 19, 45, 130, 21, 51, 2, 37, 49, 68] [71, 45, 21, 51, 2, 37, 49, 68]
Approach: pmi user_id: 261 [19, 40, 44, 7, 37, 49, 61, 48] [19, 40, 43, 7, 49, 61, 48]
Approach: adaptive user_id: 265 [97, 94, 21, 25, 22, 18, 33] [97, 20, 94, 44, 43, 25, 22, 68, 57, 60, 33]
Approach: pmi user_id: 269 [97, 78, 116, 19, 82, 74, 28, 39, 34, 13] [97, 116, 74, 28, 39, 34, 13, 120]
Approach: adaptive user_id: 272 [78, 19, 112, 18, 49] [78, 19, 13, 18, 49]
Approach: pmi user_id: 276 [74, 21, 18, 57, 60] [74, 11, 21, 25, 2, 18, 57, 60]
Approach: adaptive user_id: 278 [78, 74, 120, 2, 37, 49, 57, 48] [78, 37, 49, 31, 57, 48]
Approach: pmi user_id: 284 [71, 74, 21, 32, 25, 18, 61, 57] [71, 74, 21, 25, 18, 61]
Approach: adaptive user_id: 287 [71, 82, 21, 51, 18, 84, 37, 61, 10, 105] [71, 82, 21, 18, 84, 37, 61, 10, 105]
Approach: pmi user_id: 292 [4, 135, 32, 2, 102, 89, 42, 57, 123, 105] [135, 32, 102, 89, 42, 57, 123]
Approach: adaptive user_id: 294 [20, 4, 71, 82, 28, 43, 13, 51, 66, 25] [2, 102, 50, 18, 75]
Approach: pmi user_id: 298 [71, 19, 11, 21, 103, 102, 18, 68] [71, 103, 2, 18, 68, 57, 60]
Approach: adaptive user_id: 301 [78, 82, 74, 25, 102, 18, 37, 57] [78, 32, 102, 18, 57]
Approach: pmi user_id: 303 [20, 71, 45, 13, 103, 25, 22, 2, 85, 9] [97, 20, 71, 19, 21, 120, 25, 22, 2, 85]
Approach: adaptive user_id: 309 [97, 135, 17, 1, 22, 48] [97, 17, 22, 65, 48]
Approach: pmi user_id: 315 [97, 4, 82, 32, 25, 7, 49, 57, 128] [97, 4, 63, 82, 72, 32, 25, 7, 102, 49, 42, 57, 128, 105]
Approach: adaptive user_id: 318 [78, 20, 28, 21, 36, 18, 84, 15, 53, 57] [78, 20, 21, 32, 36, 18, 84, 49, 15, 53, 57]
Approach: adaptive user_id: 321 [78, 66, 17, 50, 48] [78, 66, 17, 50, 48]
Approach: adaptive user_id: 325 [71, 34, 32, 102, 37, 60] [32, 102, 37, 57, 60]
Approach: pmi user_id: 327 [71, 34, 21, 36, 2, 18] [71, 34, 21, 36, 2, 18]
Approach: adaptive user_id: 329 [116, 19, 115, 95, 22, 90, 15, 26, 104, 48] [116, 19, 115, 95, 22, 90, 15, 26, 104, 48]
Approach: pmi user_id: 334 [82, 94, 34, 13, 103, 111, 37] [82, 94, 34, 13, 103, 111, 37]
Approach: pmi user_id: 339 [74, 95, 66, 32, 85] [74, 66, 18, 85, 57]
Approach: pmi user_id: 341 [40, 28, 96, 92, 57, 60] [40, 28, 96, 57]
Approach: pmi user_id: 344 [97, 78, 21, 7, 18] [21, 18, 57, 133, 128]
Approach: pmi user_id: 349 [97, 20, 82, 2, 102, 68, 57, 60, 48, 133] [97, 7, 2, 57, 60, 48, 133]
Approach: adaptive user_id: 351 [4, 71, 21, 25, 49, 105] [20, 4, 71, 21, 25, 111, 49, 57, 23, 105, 33]
Approach: pmi user_id: 354 [71, 32, 29, 18, 33] [4, 71, 18, 37, 48, 33]
Approach: adaptive user_id: 356 [28, 66, 32, 111, 100, 134, 61, 42, 57, 105] [32, 100, 134, 61, 42, 105]

In [123]:
for k, v in user_interested_topics_dict.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    removed = list(set(v['pre']) - set(v['post']))
    added = list(set(v['post']) - set(v['pre']))
    
    print("Approach:", app,  "user_id:", k, removed, added)

Approach: adaptive user_id: 237 [80, 51] []
Approach: adaptive user_id: 249 [130, 19] []
Approach: pmi user_id: 261 [44, 37] [43]
Approach: adaptive user_id: 265 [18, 21] [68, 43, 44, 20, 57, 60]
Approach: pmi user_id: 269 [82, 19, 78] [120]
Approach: adaptive user_id: 272 [112] [13]
Approach: pmi user_id: 276 [] [25, 2, 11]
Approach: adaptive user_id: 278 [120, 2, 74] [31]
Approach: pmi user_id: 284 [32, 57] []
Approach: adaptive user_id: 287 [51] []
Approach: pmi user_id: 292 [105, 2, 4] []
Approach: adaptive user_id: 294 [66, 4, 71, 43, 13, 82, 51, 20, 25, 28] [2, 102, 75, 18, 50]
Approach: pmi user_id: 298 [19, 11, 21, 102] [57, 2, 60]
Approach: adaptive user_id: 301 [25, 74, 82, 37] [32]
Approach: pmi user_id: 303 [9, 45, 13, 103] [120, 97, 19, 21]
Approach: adaptive user_id: 309 [1, 135] [65]
Approach: pmi user_id: 315 [] [102, 72, 105, 42, 63]
Approach: adaptive user_id: 318 [28] [32, 49]
Approach: adaptive user_id: 321 [] []
Approach: adaptive user_id: 325 [34, 71] [57]
Approach: pmi user_id: 327 [] []
Approach: adaptive user_id: 329 [] []
Approach: pmi user_id: 334 [] []
Approach: pmi user_id: 339 [32, 95] [57, 18]
Approach: pmi user_id: 341 [60, 92] []
Approach: pmi user_id: 344 [97, 78, 7] [128, 57, 133]
Approach: pmi user_id: 349 [82, 68, 20, 102] [7]
Approach: adaptive user_id: 351 [] [33, 111, 20, 23, 57]
Approach: pmi user_id: 354 [32, 29] [48, 4, 37]
Approach: adaptive user_id: 356 [57, 66, 28, 111] []

In [122]:
just_add = 0 
just_remove = 0
both = 0
r = 0 
for k, v in user_interested_topics_dict.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    removed = list(set(v['pre']) - set(v['post']))
    added = list(set(v['post']) - set(v['pre']))
    if len(removed) == 0 and len(added) > 0:
        just_add=just_add+1
    elif len(added) == 0 and len(removed) > 0:
        just_remove=just_remove+1
    elif len(removed) > 0 and len(added) > 0:
        both = both+1
    else:
        print(added, removed)
print(just_add, just_remove, both)

[] []
[] []
[] []
[] []
3 7 16

In [10]:
add_topic_dict = dict()
remove_topic_dict = dict()
for k, v in user_interested_topics_dict.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    removed = list(set(v['pre']) - set(v['post']))
    added = list(set(v['post']) - set(v['pre']))
    add_topic_dict[k] = added
    remove_topic_dict[k] = removed
    #print("Approach:", app,  "user_id:", k, removed, added)

In [17]:
add_topic_dict

{237: [],
 249: [],
 261: [43],
 265: [68, 43, 44, 20, 57, 60],
 269: [120],
 272: [13],
 276: [25, 2, 11],
 278: [31],
 284: [],
 287: [],
 292: [],
 294: [2, 102, 75, 18, 50],
 298: [57, 2, 60],
 301: [32],
 303: [120, 97, 19, 21],
 309: [65],
 315: [102, 72, 105, 42, 63],
 318: [32, 49],
 321: [],
 325: [57],
 327: [],
 329: [],
 334: [],
 339: [57, 18],
 341: [],
 344: [128, 57, 133],
 349: [7],
 351: [33, 111, 20, 23, 57],
 354: [48, 4, 37],
 356: []}

In [19]:
remove_topic_dict

{237: [80, 51],
 249: [130, 19],
 261: [44, 37],
 265: [18, 21],
 269: [82, 19, 78],
 272: [112],
 276: [],
 278: [120, 2, 74],
 284: [32, 57],
 287: [51],
 292: [105, 2, 4],
 294: [66, 4, 71, 43, 13, 82, 51, 20, 25, 28],
 298: [19, 11, 21, 102],
 301: [25, 74, 82, 37],
 303: [9, 45, 13, 103],
 309: [1, 135],
 315: [],
 318: [28],
 321: [],
 325: [34, 71],
 327: [],
 329: [],
 334: [],
 339: [32, 95],
 341: [60, 92],
 344: [97, 78, 7],
 349: [82, 68, 20, 102],
 351: [],
 354: [32, 29],
 356: [57, 66, 28, 111]}

# User topic interest before (pre) and after (post) using StumbleOn

# End HERE!!

In [20]:
cat_ids = pd.read_csv('category_ids.csv')

In [21]:
def get_topic_name(id_):
    return cat_ids[cat_ids['id']==id_].name.values[0]

In [22]:
with open('pre_preference.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    for k, v in user_interested_topics_dict.items():
        #app = users_approaches[users_approaches['user_id']==k].approach.values[0]
        for item in v['pre']:
            pref_pre = pre_cats_interest_df[(pre_cats_interest_df['user_id'] == k) & (pre_cats_interest_df['category_id'] == item)].preference.values[0]
            topic_name = get_topic_name(item)
            writer.writerow([k, topic_name, pref_pre])

In [23]:
with open('post_preference.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    for k, v in user_interested_topics_dict.items():
        #app = users_approaches[users_approaches['user_id']==k].approach.values[0]
        for item in v['post']:
            pref_post = post_cats_interest_df[(post_cats_interest_df['user_id'] == k) & (post_cats_interest_df['category_id'] == item)].post_preference.values[0]
            topic_name = get_topic_name(item)
            writer.writerow([k, topic_name, pref_post])

In [24]:
for k1, v1 in v.items():
        for t in v1:
            pref_pre = pre_cats_interest_df[(pre_cats_interest_df['user_id'] == k) & (pre_cats_interest_df['category_id'] == t)].preference.values[0]
            pref_post = post_cats_interest_df[(post_cats_interest_df['user_id'] == k) & (post_cats_interest_df['category_id'] == t)].post_preference.values[0]
            print(k, t, pref_pre, pref_post)

IndexError: index 0 is out of bounds for axis 0 with size 0

# Similar Topics before and after using StumbleOn

In [27]:
similar_topics_dict = defaultdict(list)
for user_id in users_ids:
    pre =  pre_cats_interest_df[pre_cats_interest_df['user_id'] == user_id].category_id
    post = post_cats_interest_df[post_cats_interest_df['user_id'] == user_id].category_id
    similar_topics_dict[user_id] = set(pre) & set(post)

In [28]:
similar_topics_dict

defaultdict(list,
            {237: {2, 66, 105, 115},
             249: {2, 21, 37, 45, 49, 51, 68, 71},
             261: {7, 19, 40, 48, 49, 61},
             265: {22, 25, 33, 94, 97},
             269: {13, 28, 34, 39, 74, 97, 116},
             272: {18, 19, 49, 78},
             276: {18, 21, 57, 60, 74},
             278: {37, 48, 49, 57, 78},
             284: {18, 21, 25, 61, 71, 74},
             287: {10, 18, 21, 37, 61, 71, 82, 84, 105},
             292: {32, 42, 57, 89, 102, 123, 135},
             294: set(),
             298: {18, 68, 71, 103},
             301: {18, 57, 78, 102},
             303: {2, 20, 22, 25, 71, 85},
             309: {17, 22, 48, 97},
             315: {4, 7, 25, 32, 49, 57, 82, 97, 128},
             318: {15, 18, 20, 21, 36, 53, 57, 78, 84},
             321: {17, 48, 50, 66, 78},
             325: {32, 37, 60, 102},
             327: {2, 18, 21, 34, 36, 71},
             329: {15, 19, 22, 26, 48, 90, 95, 104, 115, 116},
             334: {13, 34, 37, 82, 94, 103, 111},
             339: {66, 74, 85},
             341: {28, 40, 57, 96},
             344: {18, 21},
             349: {2, 48, 57, 60, 97, 133},
             351: {4, 21, 25, 49, 71, 105},
             354: {18, 33, 71},
             356: {32, 42, 61, 100, 105, 134}})

# Topic preference before and after using StumbleOn

In [29]:
topic_preference_change_per_user = defaultdict(dict)
for u_id, topic_list in similar_topics_dict.items():
    for t in topic_list:
        pref_pre = pre_cats_interest_df[(pre_cats_interest_df['user_id'] == u_id) & (pre_cats_interest_df['category_id'] == t)].preference.values[0]
        pref_post = post_cats_interest_df[(post_cats_interest_df['user_id'] == u_id) & (post_cats_interest_df['category_id'] == t)].post_preference.values[0]
        topic_preference_change_per_user[u_id][t] = [pref_pre, pref_post]

In [30]:
for k, v in topic_preference_change_per_user.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    print("Approach:", app,  "user_id:", k, v)

Approach: adaptive user_id: 237 {105: [4, 4], 2: [5, 3], 115: [4, 2], 66: [2, 4]}
Approach: adaptive user_id: 249 {2: [5, 5], 68: [3, 5], 37: [1, 4], 71: [5, 4], 45: [5, 5], 49: [1, 3], 51: [2, 3], 21: [4, 5]}
Approach: pmi user_id: 261 {7: [4, 3], 40: [4, 3], 48: [5, 5], 49: [4, 3], 19: [3, 4], 61: [5, 3]}
Approach: adaptive user_id: 265 {97: [5, 5], 33: [5, 5], 22: [5, 5], 25: [4, 4], 94: [5, 5]}
Approach: pmi user_id: 269 {97: [5, 3], 34: [1, 2], 39: [5, 3], 74: [1, 1], 13: [2, 4], 116: [5, 4], 28: [4, 3]}
Approach: adaptive user_id: 272 {49: [4, 4], 18: [3, 4], 19: [3, 3], 78: [5, 5]}
Approach: pmi user_id: 276 {74: [2, 3], 18: [5, 5], 21: [3, 4], 57: [1, 5], 60: [4, 4]}
Approach: adaptive user_id: 278 {37: [4, 4], 78: [5, 5], 48: [5, 3], 49: [5, 4], 57: [2, 2]}
Approach: pmi user_id: 284 {71: [4, 4], 74: [3, 3], 18: [5, 5], 21: [5, 5], 25: [1, 2], 61: [5, 3]}
Approach: adaptive user_id: 287 {37: [4, 4], 71: [4, 3], 105: [5, 5], 10: [5, 5], 82: [3, 2], 18: [5, 5], 84: [4, 3], 21: [5, 3], 61: [5, 4]}
Approach: pmi user_id: 292 {32: [4, 4], 102: [2, 2], 135: [5, 5], 42: [4, 4], 89: [2, 3], 123: [4, 2], 57: [3, 2]}
Approach: pmi user_id: 298 {18: [4, 3], 68: [4, 4], 71: [5, 5], 103: [2, 2]}
Approach: adaptive user_id: 301 {78: [5, 4], 18: [5, 5], 102: [4, 4], 57: [4, 5]}
Approach: pmi user_id: 303 {2: [2, 1], 71: [5, 5], 20: [5, 3], 85: [5, 5], 22: [5, 5], 25: [4, 2]}
Approach: adaptive user_id: 309 {48: [5, 3], 97: [4, 4], 17: [3, 1], 22: [4, 2]}
Approach: pmi user_id: 315 {32: [5, 5], 97: [5, 5], 128: [4, 5], 4: [5, 5], 7: [5, 5], 49: [5, 5], 82: [5, 5], 25: [5, 5], 57: [4, 5]}
Approach: adaptive user_id: 318 {36: [4, 4], 78: [2, 4], 15: [3, 1], 18: [4, 3], 20: [1, 3], 21: [5, 5], 84: [1, 1], 53: [5, 4], 57: [2, 3]}
Approach: adaptive user_id: 321 {66: [3, 5], 78: [2, 5], 48: [1, 5], 17: [5, 5], 50: [4, 5]}
Approach: adaptive user_id: 325 {32: [4, 3], 60: [4, 2], 37: [5, 4], 102: [4, 2]}
Approach: pmi user_id: 327 {34: [5, 4], 2: [5, 1], 36: [5, 5], 71: [5, 4], 18: [5, 5], 21: [5, 5]}
Approach: adaptive user_id: 329 {90: [5, 4], 104: [4, 5], 15: [3, 4], 48: [4, 4], 115: [4, 3], 19: [1, 3], 116: [5, 5], 22: [4, 1], 26: [3, 3], 95: [4, 3]}
Approach: pmi user_id: 334 {34: [3, 4], 37: [2, 3], 103: [1, 3], 13: [5, 5], 111: [1, 1], 82: [1, 2], 94: [4, 3]}
Approach: pmi user_id: 339 {66: [3, 2], 85: [3, 3], 74: [4, 3]}
Approach: pmi user_id: 341 {40: [5, 5], 57: [3, 4], 28: [4, 5], 96: [5, 4]}
Approach: pmi user_id: 344 {18: [5, 4], 21: [5, 4]}
Approach: pmi user_id: 349 {97: [3, 3], 2: [4, 5], 133: [3, 4], 48: [5, 5], 57: [5, 5], 60: [5, 4]}
Approach: adaptive user_id: 351 {4: [4, 4], 71: [5, 4], 105: [1, 1], 49: [5, 5], 21: [3, 4], 25: [2, 1]}
Approach: pmi user_id: 354 {33: [3, 1], 18: [5, 2], 71: [4, 5]}
Approach: adaptive user_id: 356 {32: [1, 4], 100: [4, 3], 134: [4, 5], 105: [5, 1], 42: [5, 5], 61: [1, 2]}

In [31]:
for k, v in topic_preference_change_per_user.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    print("Approach:", app,  "user_id:", k, v)

Approach: adaptive user_id: 237 {105: [4, 4], 2: [5, 3], 115: [4, 2], 66: [2, 4]}
Approach: adaptive user_id: 249 {2: [5, 5], 68: [3, 5], 37: [1, 4], 71: [5, 4], 45: [5, 5], 49: [1, 3], 51: [2, 3], 21: [4, 5]}
Approach: pmi user_id: 261 {7: [4, 3], 40: [4, 3], 48: [5, 5], 49: [4, 3], 19: [3, 4], 61: [5, 3]}
Approach: adaptive user_id: 265 {97: [5, 5], 33: [5, 5], 22: [5, 5], 25: [4, 4], 94: [5, 5]}
Approach: pmi user_id: 269 {97: [5, 3], 34: [1, 2], 39: [5, 3], 74: [1, 1], 13: [2, 4], 116: [5, 4], 28: [4, 3]}
Approach: adaptive user_id: 272 {49: [4, 4], 18: [3, 4], 19: [3, 3], 78: [5, 5]}
Approach: pmi user_id: 276 {74: [2, 3], 18: [5, 5], 21: [3, 4], 57: [1, 5], 60: [4, 4]}
Approach: adaptive user_id: 278 {37: [4, 4], 78: [5, 5], 48: [5, 3], 49: [5, 4], 57: [2, 2]}
Approach: pmi user_id: 284 {71: [4, 4], 74: [3, 3], 18: [5, 5], 21: [5, 5], 25: [1, 2], 61: [5, 3]}
Approach: adaptive user_id: 287 {37: [4, 4], 71: [4, 3], 105: [5, 5], 10: [5, 5], 82: [3, 2], 18: [5, 5], 84: [4, 3], 21: [5, 3], 61: [5, 4]}
Approach: pmi user_id: 292 {32: [4, 4], 102: [2, 2], 135: [5, 5], 42: [4, 4], 89: [2, 3], 123: [4, 2], 57: [3, 2]}
Approach: pmi user_id: 298 {18: [4, 3], 68: [4, 4], 71: [5, 5], 103: [2, 2]}
Approach: adaptive user_id: 301 {78: [5, 4], 18: [5, 5], 102: [4, 4], 57: [4, 5]}
Approach: pmi user_id: 303 {2: [2, 1], 71: [5, 5], 20: [5, 3], 85: [5, 5], 22: [5, 5], 25: [4, 2]}
Approach: adaptive user_id: 309 {48: [5, 3], 97: [4, 4], 17: [3, 1], 22: [4, 2]}
Approach: pmi user_id: 315 {32: [5, 5], 97: [5, 5], 128: [4, 5], 4: [5, 5], 7: [5, 5], 49: [5, 5], 82: [5, 5], 25: [5, 5], 57: [4, 5]}
Approach: adaptive user_id: 318 {36: [4, 4], 78: [2, 4], 15: [3, 1], 18: [4, 3], 20: [1, 3], 21: [5, 5], 84: [1, 1], 53: [5, 4], 57: [2, 3]}
Approach: adaptive user_id: 321 {66: [3, 5], 78: [2, 5], 48: [1, 5], 17: [5, 5], 50: [4, 5]}
Approach: adaptive user_id: 325 {32: [4, 3], 60: [4, 2], 37: [5, 4], 102: [4, 2]}
Approach: pmi user_id: 327 {34: [5, 4], 2: [5, 1], 36: [5, 5], 71: [5, 4], 18: [5, 5], 21: [5, 5]}
Approach: adaptive user_id: 329 {90: [5, 4], 104: [4, 5], 15: [3, 4], 48: [4, 4], 115: [4, 3], 19: [1, 3], 116: [5, 5], 22: [4, 1], 26: [3, 3], 95: [4, 3]}
Approach: pmi user_id: 334 {34: [3, 4], 37: [2, 3], 103: [1, 3], 13: [5, 5], 111: [1, 1], 82: [1, 2], 94: [4, 3]}
Approach: pmi user_id: 339 {66: [3, 2], 85: [3, 3], 74: [4, 3]}
Approach: pmi user_id: 341 {40: [5, 5], 57: [3, 4], 28: [4, 5], 96: [5, 4]}
Approach: pmi user_id: 344 {18: [5, 4], 21: [5, 4]}
Approach: pmi user_id: 349 {97: [3, 3], 2: [4, 5], 133: [3, 4], 48: [5, 5], 57: [5, 5], 60: [5, 4]}
Approach: adaptive user_id: 351 {4: [4, 4], 71: [5, 4], 105: [1, 1], 49: [5, 5], 21: [3, 4], 25: [2, 1]}
Approach: pmi user_id: 354 {33: [3, 1], 18: [5, 2], 71: [4, 5]}
Approach: adaptive user_id: 356 {32: [1, 4], 100: [4, 3], 134: [4, 5], 105: [5, 1], 42: [5, 5], 61: [1, 2]}

In [16]:
cat_ids = pd.read_csv('category_ids.csv')

In [19]:
for k, v in topic_preference_change_per_user.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    #cat = cat_ids[cat_ids]
    for k1,v1 in v.items():
        print(app, k, v1)

adaptive 237 [4, 4]
adaptive 237 [5, 3]
adaptive 237 [4, 2]
adaptive 237 [2, 4]
adaptive 249 [5, 5]
adaptive 249 [3, 5]
adaptive 249 [1, 4]
adaptive 249 [5, 4]
adaptive 249 [5, 5]
adaptive 249 [1, 3]
adaptive 249 [2, 3]
adaptive 249 [4, 5]
pmi 261 [4, 3]
pmi 261 [4, 3]
pmi 261 [5, 5]
pmi 261 [4, 3]
pmi 261 [3, 4]
pmi 261 [5, 3]
adaptive 265 [5, 5]
adaptive 265 [5, 5]
adaptive 265 [5, 5]
adaptive 265 [4, 4]
adaptive 265 [5, 5]
pmi 269 [5, 3]
pmi 269 [1, 2]
pmi 269 [5, 3]
pmi 269 [1, 1]
pmi 269 [2, 4]
pmi 269 [5, 4]
pmi 269 [4, 3]
adaptive 272 [4, 4]
adaptive 272 [3, 4]
adaptive 272 [3, 3]
adaptive 272 [5, 5]
pmi 276 [2, 3]
pmi 276 [5, 5]
pmi 276 [3, 4]
pmi 276 [1, 5]
pmi 276 [4, 4]
adaptive 278 [4, 4]
adaptive 278 [5, 5]
adaptive 278 [5, 3]
adaptive 278 [5, 4]
adaptive 278 [2, 2]
pmi 284 [4, 4]
pmi 284 [3, 3]
pmi 284 [5, 5]
pmi 284 [5, 5]
pmi 284 [1, 2]
pmi 284 [5, 3]
adaptive 287 [4, 4]
adaptive 287 [4, 3]
adaptive 287 [5, 5]
adaptive 287 [5, 5]
adaptive 287 [3, 2]
adaptive 287 [5, 5]
adaptive 287 [4, 3]
adaptive 287 [5, 3]
adaptive 287 [5, 4]
pmi 292 [4, 4]
pmi 292 [2, 2]
pmi 292 [5, 5]
pmi 292 [4, 4]
pmi 292 [2, 3]
pmi 292 [4, 2]
pmi 292 [3, 2]
pmi 298 [4, 3]
pmi 298 [4, 4]
pmi 298 [5, 5]
pmi 298 [2, 2]
adaptive 301 [5, 4]
adaptive 301 [5, 5]
adaptive 301 [4, 4]
adaptive 301 [4, 5]
pmi 303 [2, 1]
pmi 303 [5, 5]
pmi 303 [5, 3]
pmi 303 [5, 5]
pmi 303 [5, 5]
pmi 303 [4, 2]
adaptive 309 [5, 3]
adaptive 309 [4, 4]
adaptive 309 [3, 1]
adaptive 309 [4, 2]
pmi 315 [5, 5]
pmi 315 [5, 5]
pmi 315 [4, 5]
pmi 315 [5, 5]
pmi 315 [5, 5]
pmi 315 [5, 5]
pmi 315 [5, 5]
pmi 315 [5, 5]
pmi 315 [4, 5]
adaptive 318 [4, 4]
adaptive 318 [2, 4]
adaptive 318 [3, 1]
adaptive 318 [4, 3]
adaptive 318 [1, 3]
adaptive 318 [5, 5]
adaptive 318 [1, 1]
adaptive 318 [5, 4]
adaptive 318 [2, 3]
adaptive 321 [3, 5]
adaptive 321 [2, 5]
adaptive 321 [1, 5]
adaptive 321 [5, 5]
adaptive 321 [4, 5]
adaptive 325 [4, 3]
adaptive 325 [4, 2]
adaptive 325 [5, 4]
adaptive 325 [4, 2]
pmi 327 [5, 4]
pmi 327 [5, 1]
pmi 327 [5, 5]
pmi 327 [5, 4]
pmi 327 [5, 5]
pmi 327 [5, 5]
adaptive 329 [5, 4]
adaptive 329 [4, 5]
adaptive 329 [3, 4]
adaptive 329 [4, 4]
adaptive 329 [4, 3]
adaptive 329 [1, 3]
adaptive 329 [5, 5]
adaptive 329 [4, 1]
adaptive 329 [3, 3]
adaptive 329 [4, 3]
pmi 334 [3, 4]
pmi 334 [2, 3]
pmi 334 [1, 3]
pmi 334 [5, 5]
pmi 334 [1, 1]
pmi 334 [1, 2]
pmi 334 [4, 3]
pmi 339 [3, 2]
pmi 339 [3, 3]
pmi 339 [4, 3]
pmi 341 [5, 5]
pmi 341 [3, 4]
pmi 341 [4, 5]
pmi 341 [5, 4]
pmi 344 [5, 4]
pmi 344 [5, 4]
pmi 349 [3, 3]
pmi 349 [4, 5]
pmi 349 [3, 4]
pmi 349 [5, 5]
pmi 349 [5, 5]
pmi 349 [5, 4]
adaptive 351 [4, 4]
adaptive 351 [5, 4]
adaptive 351 [1, 1]
adaptive 351 [5, 5]
adaptive 351 [3, 4]
adaptive 351 [2, 1]
pmi 354 [3, 1]
pmi 354 [5, 2]
pmi 354 [4, 5]
adaptive 356 [1, 4]
adaptive 356 [4, 3]
adaptive 356 [4, 5]
adaptive 356 [5, 1]
adaptive 356 [5, 5]
adaptive 356 [1, 2]

In [31]:
cat_ids

      id                                       name
0      1                          Flu / Cold / SARS
1      2                     IT / Internet / E-mail
2      3             Pediatrics / Children's Health
3      4                                    Allergy
4      5                         Eczema / Psoriasis
5      6               CJD / vCJD / Mad Cow Disease
6      7                   Immune System / Vaccines
7      8                     Pregnancy / Obstetrics
8      9                     Smoking / Quit Smoking
9     10                   Veterans / Ex-Servicemen
10    11                                  Dentistry
11    12                     Alzheimer's / Dementia
12    13                                   Diabetes
13    14                                    Statins
14    15                        Preventive Medicine
15    16   Infectious Diseases / Bacteria / Viruses
16    17                                  Fertility
17    18                              Mental Health
18    19                                     Autism
19    20        Alcohol / Addiction / Illegal Drugs
20    21                                 Depression
21    22                                 HIV / AIDS
22    23                                     Stroke
23    24                             Ovarian Cancer
24    25                        Headache / Migraine
25    26            Primary Care / General Practice
26    27                              Endocrinology
27    28                          Cancer / Oncology
28    29                               Hypertension
29    30                       Respiratory / Asthma
..   ...                                        ...
105  106                          Tropical Diseases
106  107                                      Lupus
107  108                               Fibromyalgia
108  109                        Huntingtons Disease
109  110                                       Gout
110  111       Health Insurance / Medical Insurance
111  112              Clinical Trials / Drug Trials
112  113                                   Vascular
113  114                   Irritable-Bowel Syndrome
114  115                       Ear, Nose and Throat
115  116                            Aid / Disasters
116  117                   Irritable Bowel Syndrome
117  118                      Pharmacy / Pharmacist
118  119                          Colorectal Cancer
119  120                                   Epilepsy
120  121                         Acid Reflux / GERD
121  122                                Conferences
122  123                                 Veterinary
123  124                               Cleft Palate
124  125              Cervical Cancer / HPV Vaccine
125  126                Medical Practice Management
126  127                                 Body Aches
127  128                                  Swine Flu
128  129                       Huntington's Disease
129  130                                 Compliance
130  131  Personal Monitoring / Wearable Technology
131  132                           Pulmonary System
132  133                                    Surgery
133  134                         Medical Innovation
134  135                                      Ebola

[135 rows x 2 columns]

In [35]:
increased_pref_topic_count = 0
decreased_pref_topic_count = 0
fixed_pref_topic_count = 0
for k, v in topic_preference_change_per_user.items():
    app = users_approaches[users_approaches['user_id']==k].approach.values[0]
    for k1, v1 in v.items():
        if v1[0]>v1[1]:
            decreased_pref_topic_count = decreased_pref_topic_count+1
        elif v1[0]<v1[1]:
            increased_pref_topic_count = increased_pref_topic_count+1
        else:
            fixed_pref_topic_count = fixed_pref_topic_count+1
print(increased_pref_topic_count, decreased_pref_topic_count, fixed_pref_topic_count)

41 56 67

# Reason

In [36]:
search_results_df = pd.read_csv('./results/stumbleon2_usersearchresult.csv')

In [112]:
search_results_df

        id  session_num  article_id  category_id  user_id
0     3138            1      102984          105      237
1     3139            1       97696           80      237
2     3140            1      207476          115      237
3     3141            1      267494           51      237
4     3142            1       67191           80      237
5     3143            1      161580            2      237
6     3144            1      110568           66      237
7     3145            1      269035           66      237
8     3146            1       67515            2      237
9     3147            1      123756          105      237
10    3148            1      245196           51      237
11    3149            1       97101          115      237
12    3150            2      253090          115      237
13    3151            2      273412           51      237
14    3152            2      231765           66      237
15    3153            2       97626          105      237
16    3154            2      180765           80      237
17    3155            2       66671            2      237
18    3156            3      127458           66      237
19    3157            3      176435           51      237
20    3158            3      114469            2      237
21    3159            3      203959          105      237
22    3160            3      236394           80      237
23    3161            3       92730          115      237
24    3162            4       31273           66      237
25    3163            4       60682          115      237
26    3164            4      259932           80      237
27    3165            4      207037            2      237
28    3166            4      218574           51      237
29    3167            4       75919          105      237
...    ...          ...         ...          ...      ...
2772  6080            9      221213          134      356
2773  6081            9      259966          111      356
2774  6082            9      224485           42      356
2775  6083           10      185980          105      356
2776  6084           10      259778           28      356
2777  6085           10      139484           66      356
2778  6086           10       67238           32      356
2779  6087           10      191111           42      356
2780  6088           10      170729           61      356
2781  6089           10      270327          100      356
2782  6090           10      247580           57      356
2783  6091           10       88335          111      356
2784  6092           11      247504          134      356
2785  6093           11      170178           61      356
2786  6094           11       60021           42      356
2787  6095           11      127309          111      356
2788  6096           11      233736           28      356
2789  6097           11      116089           66      356
2790  6098           11      259227           32      356
2791  6099           11       57405           57      356
2792  6100           11      256894          105      356
2793  6101           11      176757          100      356
2794  6102           12      130128          100      356
2795  6103           12      231634          134      356
2796  6104           12      231596           66      356
2797  6105           12      169947           42      356
2798  6106           12      272444           61      356
2799  6107           12      228253           32      356
2800  6108           12      102222           28      356
2801  6109           12      271903           57      356

[2802 rows x 5 columns]

In [38]:
user_rating_df = pd.read_csv('./results/stumbleon2_userrating.csv')

In [39]:
user_rating_df

      id  user_id  useful  surprise  interest  session_num
0    144      237       3         2         3            1
1    145      237       3         4         4            2
2    146      237       4         5         5            3
3    147      237       2         3         4            4
4    148      237       4         4         3            5
5    149      237       3         4         5            5
6    150      237       3         4         4            6
7    151      237       5         5         5            7
8    152      237       4         4         4            7
9    153      237       4         5         5            8
10   154      237       4         4         3            8
11   155      237       4         3         3            9
12   156      237       4         3         4           10
13   157      237       4         3         4           11
14   158      237       4         3         3           12
15   160      249       4         4         3            1
16   161      249       2         2         2            1
17   162      249       2         3         3            1
18   163      249       4         3         5            1
19   164      249       2         4         3            2
20   165      249       3         3         3            2
21   166      249       3         4         4            2
22   167      249       4         3         5            2
23   168      249       3         5         4            3
24   169      249       5         2         4            3
25   170      249       1         2         1            3
26   171      249       1         3         1            3
27   172      249       5         3         4            4
28   173      249       2         3         2            4
29   174      249       4         4         2            5
..   ...      ...     ...       ...       ...          ...
494  639      354       4         2         4            1
495  640      354       3         4         4            2
496  641      354       5         4         5            2
497  642      354       4         3         5            3
498  643      354       5         2         5            4
499  644      354       5         4         5            4
500  645      354       5         4         5            5
501  646      354       5         5         5            5
502  647      354       4         4         4            6
503  648      354       4         4         5            7
504  649      354       5         3         5            7
505  650      354       5         1         5            8
506  651      354       4         2         4            8
507  652      354       4         4         5            9
508  653      354       4         2         3           10
509  654      354       2         3         3           11
510  655      354       5         3         4           12
511  656      354       4         3         5           12
512  657      356       1         2         2            1
513  658      356       1         3         4            2
514  659      356       1         2         3            3
515  660      356       1         3         4            4
516  661      356       1         5         5            5
517  662      356       1         3         4            6
518  663      356       1         3         3            7
519  664      356       1         3         3            8
520  665      356       1         2         4            9
521  666      356       1         1         3           10
522  667      356       1         4         5           11
523  668      356       1         1         4           12

[524 rows x 6 columns]

In [40]:
new_df = pd.merge(search_results_df, user_rating_df,  how='left', left_on=['session_num', 'user_id'], right_on = ['session_num', 'user_id'])

In [41]:
new_df

,id_x,session_num,article_id,category_id,user_id,id_y,useful,surprise,interest
0,3138,1,102984,105,237,144,3,2,3
1,3139,1,97696,80,237,144,3,2,3
2,3140,1,207476,115,237,144,3,2,3
3,3141,1,267494,51,237,144,3,2,3
4,3142,1,67191,80,237,144,3,2,3
5,3143,1,161580,2,237,144,3,2,3
6,3144,1,110568,66,237,144,3,2,3
7,3145,1,269035,66,237,144,3,2,3
8,3146,1,67515,2,237,144,3,2,3
9,3147,1,123756,105,237,144,3,2,3
10,3148,1,245196,51,237,144,3,2,3
11,3149,1,97101,115,237,144,3,2,3
12,3150,2,253090,115,237,145,3,4,4
13,3151,2,273412,51,237,145,3,4,4
14,3152,2,231765,66,237,145,3,4,4
15,3153,2,97626,105,237,145,3,4,4
16,3154,2,180765,80,237,145,3,4,4
17,3155,2,66671,2,237,145,3,4,4
18,3156,3,127458,66,237,146,4,5,5
19,3157,3,176435,51,237,146,4,5,5
20,3158,3,114469,2,237,146,4,5,5
21,3159,3,203959,105,237,146,4,5,5
22,3160,3,236394,80,237,146,4,5,5
23,3161,3,92730,115,237,146,4,5,5
24,3162,4,31273,66,237,147,2,3,4
25,3163,4,60682,115,237,147,2,3,4
26,3164,4,259932,80,237,147,2,3,4
27,3165,4,207037,2,237,147,2,3,4
28,3166,4,218574,51,237,147,2,3,4
29,3167,4,75919,105,237,147,2,3,4
...,...,...,...,...,...,...,...,...,...
4264,6080,9,221213,134,356,665,1,2,4
4265,6081,9,259966,111,356,665,1,2,4
4266,6082,9,224485,42,356,665,1,2,4
4267,6083,10,185980,105,356,666,1,1,3
4268,6084,10,259778,28,356,666,1,1,3
4269,6085,10,139484,66,356,666,1,1,3
4270,6086,10,67238,32,356,666,1,1,3
4271,6087,10,191111,42,356,666,1,1,3
4272,6088,10,170729,61,356,666,1,1,3
4273,6089,10,270327,100,356,666,1,1,3
4274,6090,10,247580,57,356,666,1,1,3
4275,6091,10,88335,111,356,666,1,1,3
4276,6092,11,247504,134,356,667,1,4,5
4277,6093,11,170178,61,356,667,1,4,5
4278,6094,11,60021,42,356,667,1,4,5
4279,6095,11,127309,111,356,667,1,4,5
4280,6096,11,233736,28,356,667,1,4,5
4281,6097,11,116089,66,356,667,1,4,5
4282,6098,11,259227,32,356,667,1,4,5
4283,6099,11,57405,57,356,667,1,4,5
4284,6100,11,256894,105,356,667,1,4,5
4285,6101,11,176757,100,356,667,1,4,5
4286,6102,12,130128,100,356,668,1,1,4
4287,6103,12,231634,134,356,668,1,1,4
4288,6104,12,231596,66,356,668,1,1,4
4289,6105,12,169947,42,356,668,1,1,4
4290,6106,12,272444,61,356,668,1,1,4
4291,6107,12,228253,32,356,668,1,1,4
4292,6108,12,102222,28,356,668,1,1,4
4293,6109,12,271903,57,356,668,1,1,4

In [43]:
with open('./results/stumbleon2_httprequestlog.csv', 'r') as input_file:
    log_file = input_file.readlines()

In [57]:
with open('new_logs.csv', 'w+') as new_log:
    pattern = re.compile(r"\{'\w+'\:\s\['\d+'\],\s'\w+'\:\s\['\d'\],\s'\w+'\:\s\['\d'\],\s'\w+'\:\s\['\d'\]\}",re.I)
    for line in log_file:
        if re.search(pattern, line) != None:
            new_log.write(line)
        #match = re.search(pattern,line)
        #print(match)
        #if(match): print(match.group(1))

In [90]:
new_log_df = pd.read_csv('./results/new_logs.csv', delimiter='\t')

In [94]:
import json
for index, row in new_log_df.iterrows():
    print(json.loads(row))

TypeError: the JSON object must be str, bytes or bytearray, not 'Series'

In [71]:
x = {'article_id': ['269035'], 'surprise': ['2'], 'interest': ['3'], 'useful': ['3']}

In [72]:
type(x)

dict

In [98]:
with open('./results/new_logs.csv', 'r') as f:
    rows = f.readlines()

In [109]:
with open('./results/edited_ratings.txt', 'w+') as ed:
    ed.write('user_id'+','+ 'article_id'+','+ 'surprise'+','+ 'interest'+','+ 'useful'+'\n')
    for line in rows:
        temp_dict = json.loads(line)
        ed.write(str(temp_dict['user_id'])+','+ str(temp_dict['article_id'])+','+ str(temp_dict['surprise'])+','+ str(temp_dict['interest'])+','+ str(temp_dict['useful'])+'\n')
        #print(temp_dict['article_id'], temp_dict['user_id'])

In [110]:
edited_df = pd.read_csv('./results/edited_ratings.csv')

In [111]:
edited_df

     user_id  article_id  surprise  interest  useful
0        237      269035         2         3       3
1        237      231765         4         4       3
2        237      127458         5         5       4
3        237       31273         4         3       2
4        237       31273         3         3       2
5        237       31273         3         4       2
6        237      256020         4         3       4
7        237       93946         4         5       3
8        237      253838         4         4       3
9        237      185189         5         5       5
10       237      220800         4         4       4
11       237      262294         5         5       4
12       237      266503         4         3       4
13       237      209283         3         3       4
14       237      134229         3         4       4
15       237       98701         3         4       4
16       237      249162         3         3       4
17       249      220186         4         3       4
18       249      135984         2         2       2
19       249      141703         3         3       2
20       249      117415         3         5       4
21       249      185624         4         3       2
22       249       54106         3         3       3
23       249       60335         4         4       3
24       249      163438         3         5       4
25       249      144288         5         4       3
26       249      185296         2         4       5
27       249       89619         2         1       1
28       249      225935         3         1       1
29       249      256349         3         4       5
..       ...         ...       ...       ...     ...
170      341       97708         3         4       3
171      341       57493         3         4       4
172      341      251641         5         5       5
173      341      138032         5         4       4
174      341       79127         3         3       3
175      341      197390         3         4       4
176      341       82321         3         5       3
177      341      197826         3         4       3
178      341      232302         4         4       4
179      341       47758         4         4       4
180      341      202248         4         5       3
181      341      177113         3         3       3
182      341      177113         3         2       3
183      341       46970         3         3       4
184      341       82899         5         5       4
185      341      242603         4         4       3
186      341      156413         4         4       4
187      341      145406         3         3       3
188      344      215151         2         3       2
189      344       61335         1         1       1
190      344      205678         4         3       2
191      344      244640         2         4       2
192      344      163947         4         2       1
193      344      185001         2         1       1
194      344       28265         1         1       1
195      344      270714         3         3       4
196      344      224092         2         2       1
197      344       29115         3         3       2
198      344      252034         2         3       2
199      344      259210         2         2       2

[200 rows x 5 columns]